/**
 * @fileOverview
 * A subsystem that converts currency code to its name in Russian language.
 */

const currencyNames = new Map();

function init()
{
    currencyNames.set("rub", "Российский рубль");
    currencyNames.set("usd", "Доллар США");
    currencyNames.set("eur", "Евро");
    currencyNames.set('try', 'Турецкая лира');
    currencyNames.set('kzt', 'Казахстанский тенге');
    currencyNames.set('cny', 'Китайская юань');
    currencyNames.set('uah', 'Украинская гривна');
    currencyNames.set('uzs', 'Узбекский сум');
    currencyNames.set('byn', 'Белорусский рубль');
    currencyNames.set('aed', 'Дирхам');
    currencyNames.set('btc', 'Биткоин');
    currencyNames.set('krw', 'Южнокорейская вона');
    currencyNames.set('gbp', 'Британский функт');
    currencyNames.set('amd', 'Армянский драм');
    currencyNames.set('tjs', 'Таджикистанский сомони');
    currencyNames.set('azn', 'Азербайджанский манат');
    currencyNames.set('gel', 'Грузинский лари');
    currencyNames.set('kgs', 'Кыргызский сом');
    currencyNames.set('jpy', 'Японская иена');
    currencyNames.set('xau', 'Золото');
    currencyNames.set('thb', 'Таиландский бат');
    currencyNames.set('aud', 'Австралийский доллар');
    currencyNames.set('cad', 'Канадский доллар');
    currencyNames.set('chf', 'Швейцарский франк');
    currencyNames.set('sek', 'Шведская крона');
    currencyNames.set('nzd', 'Новозеландский доллар');
    currencyNames.set('mxn', 'Мексиканский песо');
    currencyNames.set('sgd', 'Сингапурский доллар');
    currencyNames.set('hkd', 'Гонконгский доллар');
    currencyNames.set('nok', 'Норвежская крона');
    currencyNames.set('inr', 'Индийская рупия');
    currencyNames.set('brl', 'Бразильский реал');
    currencyNames.set('zar', 'Южноафриканский рэнд');
    currencyNames.set('dkk', 'Датская крона');
    currencyNames.set('pln', 'Польский злотый');
    currencyNames.set('twd', 'Тайванский доллар');
    currencyNames.set('myr', 'Малайзийский ринггит');
    currencyNames.set('ils', 'Израильский шекель');
    currencyNames.set('huf', 'Венгерский форинт');
    currencyNames.set('sar', 'Саудовская риял');
    currencyNames.set('czk', 'Чешская крона');
    currencyNames.set('idr', 'Индонезийская рупия');
    currencyNames.set('clp', 'Чилийский песо');
    currencyNames.set('cop', 'Колумбийский песо');
    currencyNames.set('ron', 'Румынский лей');
    currencyNames.set('pen', 'Перуанский соль');
    currencyNames.set('php', 'Филиппинский песо');
    currencyNames.set('kwd', 'Кувейтский динар');
    currencyNames.set('pkr', 'Пакистанский рупия');
    currencyNames.set('iqd', 'Иракский динар');
    currencyNames.set('jod', 'Иорданский динар');
    currencyNames.set('kes', 'Кенийский шиллинг');
    currencyNames.set('ars', 'Аргентинское песо');
    currencyNames.set('egp', 'Египетский фунт');
    currencyNames.set('vnd', 'Вьетнамский донг');
    currencyNames.set('qar', 'Катарский риал');
    currencyNames.set('omr', 'Оманский риал');
    currencyNames.set('bgn', 'Болгарский лев');
    currencyNames.set('tnd', 'Тунисский динар');
    currencyNames.set('mad', 'Марокканский дирхам');
    currencyNames.set('bhd', 'Бахреинский динар');
    currencyNames.set('isk', 'Исландская крона');
    currencyNames.set('lkr', 'Шри-Ланкийская рупия');
    currencyNames.set('hrk', 'Хорватская крона');
    currencyNames.set('irr', 'Иранский риал');
    currencyNames.set('ngn', 'Нигерийская наира');
    currencyNames.set('xaf', 'Франк КФА ВЕАС');
    currencyNames.set('bdt', 'Бангладешская така');
    currencyNames.set('mur', 'Мавританская рупия');
    currencyNames.set('all', 'Албанский лек');
    currencyNames.set('fjd', 'Доллар фиджи');
    currencyNames.set('xof', 'ФРАНК КФА ВСЕАО');
    currencyNames.set('bob', 'Боливийский боливиано');
    currencyNames.set('uyu', 'Уругвайское песо');
    currencyNames.set('bam', 'Конвертируемая марка');
    currencyNames.set('mkd', 'Македонский динар');
    currencyNames.set('mdl', 'Молдавский лей');
    currencyNames.set('tmt', 'Туркменский манат');
    currencyNames.set('ves', 'Венесуэльский боливар');
    currencyNames.set('dop', 'Доминиканское песо');
    currencyNames.set('dzd', 'Алжирский динар');
    currencyNames.set('xpf', 'Тихоокеанский франк');
    currencyNames.set('jmd', 'Ямайский доллар');
    currencyNames.set('ugx', 'Угандский шиллинг');
    currencyNames.set('crc', 'Костариканский колон');
    currencyNames.set('bnd', 'Брунейский доллар');
    currencyNames.set('lyd', 'Ливийский динар');
    currencyNames.set('xcd', 'Восточно-карабинский доллар');
    currencyNames.set('bbd', 'Барбадосский доллар');
    currencyNames.set('ttd', 'Доллар Тринидада и Тобаго');
    currencyNames.set('lbp', 'Ливанский фунт');
    currencyNames.set('syp', 'Сирийский фунт');
    currencyNames.set('npr', 'Непальская рупия');
    currencyNames.set('khr', 'Камбоджский риал');
    currencyNames.set('gtq', 'Гватемальский кетсаль');
    currencyNames.set('mop', 'Патака Макао');
    currencyNames.set('pyg', 'Парагвайский гуаран');
    currencyNames.set('bwp', 'Ботсванская пула');
    currencyNames.set('tzs', 'Танзанийский шиллинг');
    currencyNames.set('bsd', 'Багамский доллар');
    currencyNames.set('ang', 'Антильский гульден');
    currencyNames.set('hnl', 'Гондураская лемпира');
    currencyNames.set('nad', 'Намибийский доллар');
    currencyNames.set('etb', 'Эфиопский быр');
    currencyNames.set('cup', 'Кубинское песо');
    currencyNames.set('bmd', 'Бермудский доллар');
    currencyNames.set('nio', 'Никарагуанская кордоба');
    currencyNames.set('mwk', 'Малавикийская квача');
    currencyNames.set('pab', 'Панамский бальбоа');
    currencyNames.set('gyd', 'Гайанский доллар');
    currencyNames.set('vuv', 'Ватуу');
    currencyNames.set('htg', 'Гайтайский гурд');
    currencyNames.set('pgk', 'Папуа-Новая Гвинея');
    currencyNames.set('wst', 'Самоанская тала');
    currencyNames.set('yer', 'Йеменский риал');
    currencyNames.set('lak', 'Лаосский кип');
    currencyNames.set('gmd', 'Гамбилийский даласи');
    currencyNames.set('bzd', 'Белизский доллар');
    currencyNames.set('kyd', 'Кайманский доллар');
    currencyNames.set('kpw', 'Корейский вон');
    currencyNames.set('sdg', 'Суданский фунт');
    currencyNames.set('ssp', 'Южно-суданский фунт');
    currencyNames.set('mnt', 'Монгольский тугрик');
    currencyNames.set('mga', 'Мадагаскарский ариари');
    currencyNames.set('cve', 'Эскудо');
    currencyNames.set('aoa', 'Анголайская кванза');
    currencyNames.set('scr', 'Сейшельская рупия');
    currencyNames.set('awg', 'Арубанский флорин');
    currencyNames.set('sle', 'Сьерра-Леоне');
    currencyNames.set('gnf', 'Гвинейский франк');
    currencyNames.set('mmk', 'Мьянмай');
    currencyNames.set('rwf', 'Руандский франк');
    currencyNames.set('mvr', 'Мальдивская руфия');
    currencyNames.set('sbd', 'Доллар Соломоновых острова');
    currencyNames.set('top', 'Паанга');
    currencyNames.set('sos', 'Сомалийский шиллинг');
    currencyNames.set('djf', 'Джибутиский франк');
    currencyNames.set('bif', 'Бурундский франк');
    currencyNames.set('btn', 'Бутанский нгултай');
    currencyNames.set('lrd', 'Либертарианский доллар');
    currencyNames.set('srd', 'Суринамский доллар');
    currencyNames.set('ghs', 'Ганайский седи');
    currencyNames.set('szl', 'Свазилендский лилангени');
    currencyNames.set('ern', 'Эритрейская накфа');
    currencyNames.set('kmf', 'Коморский франк');
    currencyNames.set('mzn', 'Мозамбикский манат');
    currencyNames.set('afn', 'Афганистанский афган');
    currencyNames.set('cdf', 'Конгоанский франк');
    currencyNames.set('rsd', 'Сербский динар');
    currencyNames.set('zmw', 'Замбийский квача');
    currencyNames.set('mru', 'Мавританский угия');
    currencyNames.set('stn', 'Сан-Томе и Принсипи');
    currencyNames.set('gip', 'Гибралтарский фунт');
    currencyNames.set('eth', 'Etherium');
    currencyNames.set('bnb', 'Binance Coin');
    currencyNames.set('sol', 'Solana');
    currencyNames.set('ada', 'Cardano');
    currencyNames.set('xrp', 'Ripple');
    currencyNames.set('avax', 'Avalanche');
    currencyNames.set('dot', 'Polkadot');
    currencyNames.set('doge', 'Dogecoin');
    currencyNames.set('shib', 'Shiba Inu');
    currencyNames.set('matic', 'Polygon');
    currencyNames.set('cro', 'Cronos');
    currencyNames.set('ltc', 'Litecoin');
    currencyNames.set('uni', 'Uniswap');
    currencyNames.set('algo', 'Algorand');
    currencyNames.set('link', 'Chainlink');
    currencyNames.set('bch', 'Bitcoin Cash');
    currencyNames.set('trx', 'Tron');
    currencyNames.set('etc', 'Ethereum Classic');
    currencyNames.set('ton', 'Toncoin');
    currencyNames.set('atom', 'Cosmos');
    currencyNames.set('leo', 'Unus Sed');
    currencyNames.set('xmr', 'Monero');
    currencyNames.set('okb', 'OKB');
    currencyNames.set('xlm', 'Stellar');
    currencyNames.set('hbar', 'Hedera');
    currencyNames.set('apt', 'Aptos');
    currencyNames.set('ldo', 'Lido');
    currencyNames.set('fil', 'Filecoin');
    currencyNames.set('near', 'Near Protocol');
    currencyNames.set('vet', 'VeChain');
}

init();

export function currencyGetNameByCode(currencyCode)
{
    return currencyNames.get(currencyCode);
}
